version: '3'

services:
    python:
        image: python
        volumes:
            - .:/workspace
        tty: true
        stdin_open: true
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 1234
        expose:
            - '5432'
        volumes:
            - ./pgsql:/home
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - "PGADMIN_DEFAULT_EMAIL=admin@test.com"
            - "PGADMIN_DEFAULT_PASSWORD=1234"
        ports:
            - '8081:80'
    mongo:
        image: mongo
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
        expose:
            - '27017'
        volumes:
            - ./mongo:/home
    mongo-express:
        image: mongo-express
        ports:
            - '8082:8081'
        environment: 
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 1234


    
    